"""First migration

Revision ID: a52e3864803c
Revises: 8725a4f4e588
Create Date: 2022-05-28 18:40:56.903495

"""
import fastapi_users_db_sqlalchemy  # noqa
import sqlalchemy as sa  # noqa

from alembic import op  # noqa

# revision identifiers, used by Alembic.
revision = 'a52e3864803c'
down_revision = '8725a4f4e588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
